/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kandos
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        Nama = new java.awt.TextField();
        Kelas = new java.awt.TextField();
        Alamat = new java.awt.TextField();
        Proses = new java.awt.Button();
        Nama1 = new java.awt.TextField();
        Kelas1 = new java.awt.TextField();
        Alamat1 = new java.awt.TextField();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setText("Formulir");
        getContentPane().add(label1);
        label1.setBounds(170, 20, 60, 30);

        label2.setText("Nama");
        getContentPane().add(label2);
        label2.setBounds(60, 60, 38, 20);

        label3.setText("Kelas");
        getContentPane().add(label3);
        label3.setBounds(60, 90, 36, 20);

        label4.setText("Alamat");
        getContentPane().add(label4);
        label4.setBounds(60, 120, 42, 20);
        getContentPane().add(Nama);
        Nama.setBounds(110, 60, 210, 20);
        getContentPane().add(Kelas);
        Kelas.setBounds(110, 90, 210, 20);
        getContentPane().add(Alamat);
        Alamat.setBounds(110, 120, 210, 20);

        Proses.setLabel("Proses");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });
        getContentPane().add(Proses);
        Proses.setBounds(170, 160, 56, 24);
        getContentPane().add(Nama1);
        Nama1.setBounds(110, 220, 210, 20);
        getContentPane().add(Kelas1);
        Kelas1.setBounds(110, 250, 210, 20);
        getContentPane().add(Alamat1);
        Alamat1.setBounds(110, 280, 210, 20);

        label5.setText("Nama");
        getContentPane().add(label5);
        label5.setBounds(50, 220, 38, 20);

        label6.setText("Kelas");
        getContentPane().add(label6);
        label6.setBounds(50, 250, 36, 20);

        label7.setText("Alamat");
        getContentPane().add(label7);
        label7.setBounds(50, 280, 42, 20);

        setBounds(0, 0, 416, 416);
    }// </editor-fold>//GEN-END:initComponents

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        String nama = Nama.getText();
        Nama1.setText(nama);
        String kelas = Kelas.getText();
        Kelas1.setText(kelas);
        String alamat = Alamat.getText();
        Alamat1.setText(alamat);
    }//GEN-LAST:event_ProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Alamat;
    private java.awt.TextField Alamat1;
    private java.awt.TextField Kelas;
    private java.awt.TextField Kelas1;
    private java.awt.TextField Nama;
    private java.awt.TextField Nama1;
    private java.awt.Button Proses;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    // End of variables declaration//GEN-END:variables
}
