/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kandos
 */
public class Lat4 extends javax.swing.JFrame {

    /**
     * Creates new form Lat4
     */
    public Lat4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Absen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tek = new javax.swing.JCheckBox();
        Des = new javax.swing.JCheckBox();
        Submit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Rpl = new javax.swing.JRadioButton();
        Tkj = new javax.swing.JRadioButton();
        Prog = new javax.swing.JCheckBox();
        Anim = new javax.swing.JCheckBox();
        Hapus = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tekarea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Biodata Siswa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 20, 120, 40);
        getContentPane().add(Nama);
        Nama.setBounds(100, 70, 250, 30);
        getContentPane().add(Absen);
        Absen.setBounds(100, 110, 250, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 110, 50, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Jurusan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 160, 50, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Hobi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 190, 50, 20);

        Tek.setText("Teknisi");
        getContentPane().add(Tek);
        Tek.setBounds(230, 190, 90, 23);

        Des.setText("Designer");
        getContentPane().add(Des);
        Des.setBounds(230, 210, 90, 23);

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(70, 250, 80, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Hasil");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 290, 50, 20);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(null);

        Rpl.setText("RPL");
        jPanel1.add(Rpl);
        Rpl.setBounds(110, 160, 70, 23);

        Tkj.setText("TKJ");
        jPanel1.add(Tkj);
        Tkj.setBounds(230, 160, 93, 23);

        Prog.setText("Programing");
        jPanel1.add(Prog);
        Prog.setBounds(110, 190, 100, 23);

        Anim.setText("Animator");
        jPanel1.add(Anim);
        Anim.setBounds(110, 210, 90, 23);

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        jPanel1.add(Hapus);
        Hapus.setBounds(170, 250, 80, 30);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit);
        Exit.setBounds(270, 250, 80, 30);

        tekarea.setColumns(20);
        tekarea.setRows(5);
        jScrollPane1.setViewportView(tekarea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 310, 310, 110);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 440);

        setBounds(0, 0, 416, 478);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        String nama = Nama.getText();
        String absen = Absen.getText();
        String jurusan;
        String hobi="";
        //untuk rd
        if (Rpl.isSelected())
            jurusan = "RPL";
        else if (Tkj.isSelected())
            jurusan = "TKJ";
        else 
            jurusan = " ";
        //untuk checkbox
        if (Prog.isSelected())
            hobi+=Prog.getText()+", ";
        if (Anim.isSelected())
            hobi+=Anim.getText()+", ";
        if (Tek.isSelected())
            hobi+=Tek.getText()+", ";
        if (Des.isSelected())
            hobi+=Des.getText()+", ";
        tekarea.setText("Nama siswa : "+nama+"\n"
                + "Absen siswa : "+absen+"\n"
                + "Jurusan anda : "+jurusan+"\n"
                + "Hobi anda : "+hobi);
    }//GEN-LAST:event_SubmitActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        tekarea.setText("");
        Nama.setText("");
        Absen.setText("");
        buttonGroup1.clearSelection();
        Prog.setSelected(false);
        Anim.setSelected(false);
        Tek.setSelected(false);
        Des.setSelected(false);
    }//GEN-LAST:event_HapusActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lat4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lat4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lat4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lat4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lat4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JCheckBox Anim;
    private javax.swing.JCheckBox Des;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Hapus;
    private javax.swing.JTextField Nama;
    private javax.swing.JCheckBox Prog;
    private javax.swing.JRadioButton Rpl;
    private javax.swing.JButton Submit;
    private javax.swing.JCheckBox Tek;
    private javax.swing.JRadioButton Tkj;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tekarea;
    // End of variables declaration//GEN-END:variables
}
